title: Prakash Pandy
email: prakashpandy27@gmail.com
description: >- 
  Doubt is not a pleasant condition, but certainty is absurd. - Voltaire
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prakashpandy.com"
twitter_username: prakashpandy27
github_username:  prakashpandy

# Build settings
port: 8080
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
